# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class CreateDashboardRenderTask(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        CreateDashboardRenderTask - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'dashboard_style': 'str',
            'dashboard_filters': 'str',
            'can': 'dict(str, bool)'
        }

        self.attribute_map = {
            'dashboard_style': 'dashboard_style',
            'dashboard_filters': 'dashboard_filters',
            'can': 'can'
        }

        self._dashboard_style = None
        self._dashboard_filters = None
        self._can = None

    @property
    def dashboard_style(self):
        """
        Gets the dashboard_style of this CreateDashboardRenderTask.
        Dashboard layout style: single_column or tiled

        :return: The dashboard_style of this CreateDashboardRenderTask.
        :rtype: str
        """
        return self._dashboard_style

    @dashboard_style.setter
    def dashboard_style(self, dashboard_style):
        """
        Sets the dashboard_style of this CreateDashboardRenderTask.
        Dashboard layout style: single_column or tiled

        :param dashboard_style: The dashboard_style of this CreateDashboardRenderTask.
        :type: str
        """
        self._dashboard_style = dashboard_style

    @property
    def dashboard_filters(self):
        """
        Gets the dashboard_filters of this CreateDashboardRenderTask.
        Filter values to apply to the dashboard queries, in URL query format

        :return: The dashboard_filters of this CreateDashboardRenderTask.
        :rtype: str
        """
        return self._dashboard_filters

    @dashboard_filters.setter
    def dashboard_filters(self, dashboard_filters):
        """
        Sets the dashboard_filters of this CreateDashboardRenderTask.
        Filter values to apply to the dashboard queries, in URL query format

        :param dashboard_filters: The dashboard_filters of this CreateDashboardRenderTask.
        :type: str
        """
        self._dashboard_filters = dashboard_filters

    @property
    def can(self):
        """
        Gets the can of this CreateDashboardRenderTask.
        Operations the current user is able to perform on this object

        :return: The can of this CreateDashboardRenderTask.
        :rtype: dict(str, bool)
        """
        return self._can

    @can.setter
    def can(self, can):
        """
        Sets the can of this CreateDashboardRenderTask.
        Operations the current user is able to perform on this object

        :param can: The can of this CreateDashboardRenderTask.
        :type: dict(str, bool)
        """
        self._can = can

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

