# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class IntegrationRequiredField(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        IntegrationRequiredField - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'tag': 'str',
            'any_tag': 'list[str]',
            'all_tags': 'list[str]'
        }

        self.attribute_map = {
            'tag': 'tag',
            'any_tag': 'any_tag',
            'all_tags': 'all_tags'
        }

        self._tag = None
        self._any_tag = None
        self._all_tags = None

    @property
    def tag(self):
        """
        Gets the tag of this IntegrationRequiredField.
        Matches a field that has this tag.

        :return: The tag of this IntegrationRequiredField.
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """
        Sets the tag of this IntegrationRequiredField.
        Matches a field that has this tag.

        :param tag: The tag of this IntegrationRequiredField.
        :type: str
        """
        self._tag = tag

    @property
    def any_tag(self):
        """
        Gets the any_tag of this IntegrationRequiredField.
        If present, supercedes 'tag' and matches a field that has any of the provided tags.

        :return: The any_tag of this IntegrationRequiredField.
        :rtype: list[str]
        """
        return self._any_tag

    @any_tag.setter
    def any_tag(self, any_tag):
        """
        Sets the any_tag of this IntegrationRequiredField.
        If present, supercedes 'tag' and matches a field that has any of the provided tags.

        :param any_tag: The any_tag of this IntegrationRequiredField.
        :type: list[str]
        """
        self._any_tag = any_tag

    @property
    def all_tags(self):
        """
        Gets the all_tags of this IntegrationRequiredField.
        If present, supercedes 'tag' and matches a field that has all of the provided tags.

        :return: The all_tags of this IntegrationRequiredField.
        :rtype: list[str]
        """
        return self._all_tags

    @all_tags.setter
    def all_tags(self, all_tags):
        """
        Sets the all_tags of this IntegrationRequiredField.
        If present, supercedes 'tag' and matches a field that has all of the provided tags.

        :param all_tags: The all_tags of this IntegrationRequiredField.
        :type: list[str]
        """
        self._all_tags = all_tags

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

