# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class LookmlModelExploreSupportedMeasureType(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        LookmlModelExploreSupportedMeasureType - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'dimension_type': 'str',
            'measure_types': 'list[str]'
        }

        self.attribute_map = {
            'dimension_type': 'dimension_type',
            'measure_types': 'measure_types'
        }

        self._dimension_type = None
        self._measure_types = None

    @property
    def dimension_type(self):
        """
        Gets the dimension_type of this LookmlModelExploreSupportedMeasureType.


        :return: The dimension_type of this LookmlModelExploreSupportedMeasureType.
        :rtype: str
        """
        return self._dimension_type

    @dimension_type.setter
    def dimension_type(self, dimension_type):
        """
        Sets the dimension_type of this LookmlModelExploreSupportedMeasureType.


        :param dimension_type: The dimension_type of this LookmlModelExploreSupportedMeasureType.
        :type: str
        """
        self._dimension_type = dimension_type

    @property
    def measure_types(self):
        """
        Gets the measure_types of this LookmlModelExploreSupportedMeasureType.


        :return: The measure_types of this LookmlModelExploreSupportedMeasureType.
        :rtype: list[str]
        """
        return self._measure_types

    @measure_types.setter
    def measure_types(self, measure_types):
        """
        Sets the measure_types of this LookmlModelExploreSupportedMeasureType.


        :param measure_types: The measure_types of this LookmlModelExploreSupportedMeasureType.
        :type: list[str]
        """
        self._measure_types = measure_types

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

