# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class LookmlModelExploreFieldset(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        LookmlModelExploreFieldset - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'dimensions': 'list[LookmlModelExploreField]',
            'measures': 'list[LookmlModelExploreField]',
            'filters': 'list[LookmlModelExploreField]',
            'parameters': 'list[LookmlModelExploreField]'
        }

        self.attribute_map = {
            'dimensions': 'dimensions',
            'measures': 'measures',
            'filters': 'filters',
            'parameters': 'parameters'
        }

        self._dimensions = None
        self._measures = None
        self._filters = None
        self._parameters = None

    @property
    def dimensions(self):
        """
        Gets the dimensions of this LookmlModelExploreFieldset.
        Array of dimensions

        :return: The dimensions of this LookmlModelExploreFieldset.
        :rtype: list[LookmlModelExploreField]
        """
        return self._dimensions

    @dimensions.setter
    def dimensions(self, dimensions):
        """
        Sets the dimensions of this LookmlModelExploreFieldset.
        Array of dimensions

        :param dimensions: The dimensions of this LookmlModelExploreFieldset.
        :type: list[LookmlModelExploreField]
        """
        self._dimensions = dimensions

    @property
    def measures(self):
        """
        Gets the measures of this LookmlModelExploreFieldset.
        Array of measures

        :return: The measures of this LookmlModelExploreFieldset.
        :rtype: list[LookmlModelExploreField]
        """
        return self._measures

    @measures.setter
    def measures(self, measures):
        """
        Sets the measures of this LookmlModelExploreFieldset.
        Array of measures

        :param measures: The measures of this LookmlModelExploreFieldset.
        :type: list[LookmlModelExploreField]
        """
        self._measures = measures

    @property
    def filters(self):
        """
        Gets the filters of this LookmlModelExploreFieldset.
        Array of filters

        :return: The filters of this LookmlModelExploreFieldset.
        :rtype: list[LookmlModelExploreField]
        """
        return self._filters

    @filters.setter
    def filters(self, filters):
        """
        Sets the filters of this LookmlModelExploreFieldset.
        Array of filters

        :param filters: The filters of this LookmlModelExploreFieldset.
        :type: list[LookmlModelExploreField]
        """
        self._filters = filters

    @property
    def parameters(self):
        """
        Gets the parameters of this LookmlModelExploreFieldset.
        Array of parameters

        :return: The parameters of this LookmlModelExploreFieldset.
        :rtype: list[LookmlModelExploreField]
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters):
        """
        Sets the parameters of this LookmlModelExploreFieldset.
        Array of parameters

        :param parameters: The parameters of this LookmlModelExploreFieldset.
        :type: list[LookmlModelExploreField]
        """
        self._parameters = parameters

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

